### ISSUE TITLE
Error while running multi protos with docker

### ISSUE THREAD

**Issue by ram-98** [tokopedia/gripmock#36]
Hi ,I'm planning to use gripmock for writing integration test cases but facing issues while executing it .

`Starting GripMock
Serving stub admin on http://:4771
bar/bar.proto:8:12: "bar.Bar.name" is already defined in file "bar.proto".
bar/bar.proto:7:9: "bar.Bar" is already defined in file "bar.proto".
hello.proto: Import "bar/bar.proto" was not found or had errors.
hello.proto:9:16: "bar.Bar" seems to be defined in "bar.proto", which is not imported by "hello.proto".  To use it here, please add the necessary import.
2020/01/14 06:28:56 Fail on protoc exit status 1
`

This is the error i get while running the command 

` docker run -p 4770:4770 -p 4771:4771 -v /Desktop/gripmock/example/multi-package:/proto tkpd/gripmock --imports=/proto /proto/bar/bar.proto /proto/hello.proto /proto/foo.proto`

Any help ?

**Comment by ram-98** [comment]
@jekiapp Please help

**Comment by jekiapp** [comment]
did you see the example folder? there is an example for running multi proto files. 

Since I don't know the detail about your proto files I'm unable to help much about your problem. My suggestion is learn the example then if there is any actual issue in gripmock, feel free to write down what the issue is rather than copy pasting error message. Hope you have a great day!

**Comment by jekiapp** [comment]
duplicate  #42
