### ISSUE TITLE
Support reading from FileDescriptorSet file 

### ISSUE THREAD

**Issue by marciodel** [tokopedia/gripmock#41]
It should be possible to pass a FileDescriptorSet file as argument instead proto source files

**Comment by jekiapp** [comment]
can you elaborate more on protoset?

**Comment by marciodel** [comment]
Protoc have an option --descriptor_set_out to generate FileDescriptorSet. It would be nice if gripmock use it as input the same way that grpcurl (https://github.com/fullstorydev/grpcurl) does. In fact protoset is the name of grpcurl option.

**Comment by jekiapp** [comment]
After a little research I don't think it's possible to use FileDescriptorSet in gripmock since the `protoc` itself not supporting [it as an input](https://github.com/protocolbuffers/protobuf/issues/2725). In the case of `grpcurl` is different with gripmock, since gripmock basically generate a server based on .proto files.
