### ISSUE TITLE
Proposal: Could we generate go_package option at runtime?

### ISSUE THREAD

**Issue by HairyMike** [tokopedia/gripmock#87]
Hi there,

The recent change to require the go_package is a breaking change for us.  We primarily use nodejs and it doesn't make sense to include it in our protobufs.  Our repos are private anyway, so we'd have another step to do to make sure the gripmock image can login to our repos (I believe this triggers a 'go get' under the hood).

I'm wondering if there would be an option to generate the go_package option at runtime?  I haven't gone looking at the code just yet, but thought I'd open up a discussion on it.

I'm thinking that before we run the protoc plugin,
* copy the protobuf file (passed in the arg) to a temporary location
* parse the file, check for go_package option
* if we don't find one, generate one and add it to the file
* use the file in the temporary location to generate the client/server code

**Comment by jekiapp** [comment]
Hi @HairyMike 

I understand your concern. We all hate giving breaking changes but since we use golang for the generator, we need to comply with their plugin requirement.

But your proposal is definitely doable, even tho we need to test it rigorously. As your proposal with parsing the .proto we could give the generator plugin to have one more feature which is detecting go_package and add it if there's none.

So from the normal flow:
- receive .proto path input
- generate .pb.go files **and** server.go file (.pb.go using golang plugin, server.go using gripmock plugin)
- run stubbing server
- run grpc server


We can modify it to:
- receive .proto path input
- using gripmock plugin: detect go_package, add if there's none.
- use the processed .proto files instead of the original
- generate .pb.go files **and** server.go file (.pb.go using golang plugin, server.go using gripmock plugin)
- run stubbing server
- run grpc server

**Comment by JehandadK** [comment]
@HairyMike would be interesting if you shared whether you achieved it or not.

**Comment by HairyMike** [comment]
@JehandadK, I'll have a PR up when I get something working.  I am planning to return to this, but I've been super busy with other stuff.

**Comment by jekiapp** [comment]
I'm on it guys #101
